# For detailed configuration reference documentation, visit:
# https://supabase.com/docs/guides/local-development/cli/config
project_id = "FRONT-END"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 17

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true

# ===============================
# CONFIGURAÇÃO DAS EDGE FUNCTIONS
# ===============================

[functions.create-checkout-session]
enabled = true
verify_jwt = true

[functions.stripe-webhook]
enabled = true
verify_jwt = false # Webhooks não usam JWT

[functions.get-my-orders]
enabled = true
verify_jwt = false # Verificação manual de ID de cliente

[functions.handle-google-signin]
enabled = true
verify_jwt = false

[functions.create-mobile-checkout]
enabled = true
verify_jwt = false

# ----> INÍCIO DA CORREÇÃO <----
# Alterado para 'false' para permitir chamadas do painel de admin com login manual
[functions.sync-stripe-products]
enabled = true
verify_jwt = false 

[functions.add-stripe-product]
enabled = true
verify_jwt = false

[functions.delete-stripe-product]
enabled = true
verify_jwt = false
# ----> FIM DA CORREÇÃO <----

[functions.get-destaque-do-dia]
enabled = true
verify_jwt = false